### ISSUE TITLE
needs short lab

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/reading-ios-for-loop#4]
need short lab to follow. I feel I can't open up Xcode and try this out on my own b/c 
1. I am lazy (a little bit, but also thinking of others--it can be hard to self-motivate, especially if you don't feel sure of what you're doing). 
2. I've only used Xcode once at this point and don't even really know how to create new file/project and run it. 

@markedwardmurray

**Comment by AnnJohn** [comment]
Iceboxing for now. @markedwardmurray  close when you're done with the issue.

**Comment by markedwardmurray** [comment]
addressed with https://github.com/learn-co-curriculum/objc-fizzbuzz

https://github.com/learn-co-curriculum/mobile-development-with-ios-track/issues/15
