### ISSUE TITLE
Buffalo

### ISSUE THREAD

**Issue by anmolbajajnet** [learn-co-curriculum/reading-ios-for-loop#6]
Right under "Implementing A Loop", every "buffalo" is capitalized. 

It says "BUFFALO BUFFALO BUFFALO BUFFALO BUFFALO BUFFALO BUFFALO BUFFALO."

Instead, the text should read "Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo" as mentioned in the wikipedia and later in the lesson.

**Comment by markedwardmurray** [comment]
Looks like Learn's markdown rendering got altered recently. I changed it from an H3 header to a "bold" line so Learn doesn't uppercase it: 5bda494601edc9f05afded899763611e15b8c831

Thanks for pointing it out :+1:
